### ISSUE TITLE
Error and clarity

### ISSUE THREAD

**Issue by jkwasnik** [narcan/api-tools#2]
Hi, I'm trying to build my own version of the GA Management Magic app you created by following your instructions in Github. It's exactly what I was looking for because it's such a pain to have to update 28 custom dimensions every time we need to add a new property. So, yay! My first question is should I be using the one found here: https://chrome.google.com/webstore/detail/ga-management-magic/clmbnkmolchgmhnkbcjbadnnhekdigdo?utm_source=plus or should I build my own? 

When I try to use the one I created, I get an error saying I'm not using a proper property ID, even though the one I'm using is active and is in this format: UA-12345678-91

When I use the one on the webstore, it works. 
If I'm supposed to use the one I create, please let me know and I'll post exactly how I did it so maybe you can help me troubleshoot it. Thanks!

**Comment by narcan** [comment]
That one should be fine...building your own should not be necessary.

Your account id looks very fishy - "12345678". Are you sure that's a valid account?
